# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: alanmaikmonteiro
google_analytics: dbyll
title: Alan Monteiro

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Um blog sobre o que estou aprendendo e Vivendo na Area de tecnologia

description: Stylish Jekyll Theme
author:
  name: Alan Maik
  email: alanmaikm@gmail.com
  github: AlanMaik
  twitter: alanmaikmf
  pinterest: 
  linkedin: alan-maik-monteiro
  bio: Aprendendo e Compartilhando conhecimento!
  email_md5: 0547f61b008e8b8e6e5dd6c19b3c8b0e

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
